/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import controller.HoaDonDao;
import controller.MainDao;
import model.Combo;
import model.DatMonAn;
import model.HoaDon;
import model.ThucDon;

/**
 *
 * @author Le Tuan Minh
 */
public class MainFrm extends javax.swing.JFrame {

        DefaultTableModel model;
        DefaultTableModel hoaDon;
        private ArrayList<ThucDon> list;
        private ArrayList<Combo> listCombo;
        private int tongGia = 0;
        private long tienTra;
        private static String tenNhanVien;
        private static String nhanVienID;
        private long tongTien;
        private static int index = 3;
        private ArrayList<DatMonAn> listDatMonAn;
        private ArrayList<ThucDon> listHoaDon;
        private ArrayList<Combo> listComboHoaDon;

        /**
         * Creates new form MainFrm
         */
        public MainFrm(String tenNhanVien, String nhanVienID) {
                initComponents();
                this.tenNhanVien = tenNhanVien;
                this.nhanVienID = nhanVienID;
                txtTenNhanVien.setText(this.tenNhanVien);
                this.setLocationRelativeTo(null);
                list = new MainDao().getListMonAn();
                String[] cols = { "tên", "gía" };
                this.model = new DefaultTableModel(cols, 0) {
                        @Override
                        public boolean isCellEditable(int row, int column) {
                                return false;
                        }
                };
                list.forEach(t -> model.addRow(new Object[] {
                                t.getTen(), t.getGiaThucDon()
                }));
                this.tblTenGia.setModel(this.model);

                String[] colHoaDons = { "Tên", "Giá", "Số lượng" };
                this.hoaDon = new DefaultTableModel(colHoaDons, 0) {
                        @Override
                        public boolean isCellEditable(int row, int column) {
                                return column == 2;
                        }
                };
                this.tblHoaDon.setModel(this.hoaDon);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                btnThucDon = new javax.swing.JButton();
                btnNuocUong = new javax.swing.JButton();
                btnCombo = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblTenGia = new javax.swing.JTable();
                jPanel2 = new javax.swing.JPanel();
                btnThoat = new javax.swing.JButton();
                jPanel3 = new javax.swing.JPanel();
                jPanel6 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                btnChonBan = new javax.swing.JButton();
                tongThanhToan = new javax.swing.JLabel();
                tienTraLai = new javax.swing.JLabel();
                txtTienKhachDua = new javax.swing.JTextField();
                btnDsBan = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                tblHoaDon = new javax.swing.JTable();
                jLabel1 = new javax.swing.JLabel();
                txtTenNhanVien = new javax.swing.JTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("menu"));

                btnThucDon.setText("Thực đơn");
                btnThucDon.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnThucDonActionPerformed(evt);
                        }
                });

                btnNuocUong.setText("Nước uống");
                btnNuocUong.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNuocUongActionPerformed(evt);
                        }
                });

                btnCombo.setText("Combo");
                btnCombo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnComboActionPerformed(evt);
                        }
                });

                tblTenGia.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null },
                                                { null, null },
                                                { null, null },
                                                { null, null }
                                },
                                new String[] {
                                                "tên", "giá"
                                }) {
                        Class[] types = new Class[] {
                                        java.lang.String.class, java.lang.String.class
                        };
                        boolean[] canEdit = new boolean[] {
                                        false, false
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit[columnIndex];
                        }
                });
                tblTenGia.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tblTenGiaMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(tblTenGia);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 557,
                                                                Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(151, 151, 151)
                                                                .addComponent(btnThucDon)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnNuocUong)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnCombo)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(21, 21, 21)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnThucDon)
                                                                                .addComponent(btnNuocUong)
                                                                                .addComponent(btnCombo))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                501,
                                                                                Short.MAX_VALUE)));

                btnThoat.setText("Thoát");
                btnThoat.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnThoatActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel2Layout.createSequentialGroup()
                                                                                .addGap(0, 9, Short.MAX_VALUE)
                                                                                .addComponent(btnThoat)));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(btnThoat)
                                                                .addContainerGap()));

                jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Hoá đơn"));

                jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                jLabel3.setText("Tổng thanh toán");

                jLabel4.setText("Tiền khách đưa");

                jLabel5.setText("Tiền trả lại");

                btnChonBan.setText("Chọn bàn");
                btnChonBan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnChonBanActionPerformed(evt);
                        }
                });

                tongThanhToan.setText("0");

                tienTraLai.setText("0");

                txtTienKhachDua.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtTienKhachDuaActionPerformed(evt);
                        }
                });

                btnDsBan.setText("danh sách bàn");
                btnDsBan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDsBanActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(jPanel6Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel6Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel3)
                                                                                                                .addComponent(jLabel4)
                                                                                                                .addComponent(jLabel5))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(jPanel6Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(tongThanhToan,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(tienTraLai,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(txtTienKhachDua))
                                                                                                .addContainerGap())
                                                                                .addGroup(jPanel6Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(62, 62, 62)
                                                                                                .addComponent(btnDsBan)
                                                                                                .addGap(39, 39, 39)
                                                                                                .addComponent(btnChonBan)
                                                                                                .addContainerGap(
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)))));
                jPanel6Layout.setVerticalGroup(
                                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(tongThanhToan))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(txtTienKhachDua,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(tienTraLai))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnChonBan)
                                                                                .addComponent(btnDsBan))
                                                                .addContainerGap()));

                jScrollPane2.setViewportView(tblHoaDon);

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                                                                Short.MAX_VALUE));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(jScrollPane2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                368,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel6,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                jLabel1.setText("nhân viên");

                txtTenNhanVien.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtTenNhanVienActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jPanel3,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(21, 21, 21)
                                                                                                .addComponent(jLabel1)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(txtTenNhanVien,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                240,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addContainerGap(56,
                                                                                                                Short.MAX_VALUE)))));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel1)
                                                                                .addComponent(txtTenNhanVien,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void txtTenNhanVienActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTenNhanVienActionPerformed
        }// GEN-LAST:event_txtTenNhanVienActionPerformed

        private void btnDsBanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDsBanActionPerformed
                new DanhSachBanFrm().setVisible(true);
                Date date = java.util.Calendar.getInstance().getTime();
                System.out.println(date);
                // TODO add your handling code here:
        }// GEN-LAST:event_btnDsBanActionPerformed//
         // GEN-LAST:event_jTextField1ActionPerformed

        private void tblTenGiaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tblTenGiaMouseClicked
                // TODO add your handling code here:
                int row = this.tblTenGia.getSelectedRow();
                String ten = (String) this.tblTenGia.getValueAt(row, 0);
                Long gia = (Long) this.tblTenGia.getValueAt(row, 1);
                Integer soLuong = 1;
                this.hoaDon.addRow(new Object[] {
                                ten, gia, soLuong
                });
                tongGia += gia;
                tongThanhToan.setText(String.valueOf(tongGia));
        }// GEN-LAST:event_tblTenGiaMouseClicked

        private void btnThucDonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThucDonActionPerformed
                this.setLocationRelativeTo(null);
                list = new MainDao().getListMonAn();
                this.model.setRowCount(0);
                list.forEach(t -> model.addRow(new Object[] {
                                t.getTen(), t.getGiaThucDon()
                }));
        }// GEN-LAST:event_btnThucDonActionPerformed

        private void btnComboActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnComboActionPerformed
                this.setLocationRelativeTo(null);
                listCombo = new MainDao().getListCombo();
                this.model.setRowCount(0);
                listCombo.forEach(t -> model.addRow(new Object[] {
                                t.getTenCombo(), t.getGiaCombo()
                }));
        }// GEN-LAST:event_btnComboActionPerformed

        private void txtTienKhachDuaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTienKhachDuaActionPerformed
                Long tienKhach = Long.parseLong(txtTienKhachDua.getText());
                tienTra = tienKhach - tongGia;
                tienTraLai.setText(String.valueOf(tienTra));// TODO add your handling code here:
        }// GEN-LAST:event_txtTienKhachDuaActionPerformed

        private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {
                this.dispose();// TODO add your handling code here:
        }// GEN-LAST:event_btnThoatActionPerformed

        private void btnNuocUongActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNuocUongActionPerformed
                this.setLocationRelativeTo(null);
                list = new MainDao().getListDoUong();
                this.model.setRowCount(0);
                list.forEach(t -> model.addRow(new Object[] {
                                t.getTen(), t.getGiaThucDon()
                }));
        }// GEN-LAST:event_btnNuocUongActionPerformed

        private void btnChonBanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNuocUongActionPerformed
                if (tienTra > 0) {
                        HoaDon t = new HoaDon("HD" + index, nhanVienID, String.valueOf(tongGia), "B01");
                        new HoaDonDao().themHoaDon(t);
                        index++;
                        new BanFrm().setVisible(true);
                        String[] colHoaDons = { "Tên", "Giá", "Số lượng" };
                        this.hoaDon = new DefaultTableModel(colHoaDons, 0) {
                                @Override
                                public boolean isCellEditable(int row, int column) {
                                        return column == 2;
                                }
                        };
                        this.tblHoaDon.setModel(this.hoaDon);
                        tienTra = 0;
                        tongThanhToan.setText("");
                        txtTienKhachDua.setText("");
                        tienTraLai.setText("");
                } else {
                        JOptionPane.showMessageDialog(this, "thanh toán lỗi");
                }
        }// GEN-LAST:event_btnNuocUongActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new MainFrm(tenNhanVien, nhanVienID).setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnChonBan;
        private javax.swing.JButton btnCombo;
        private javax.swing.JButton btnDsBan;
        private javax.swing.JButton btnNuocUong;
        private javax.swing.JButton btnThoat;
        private javax.swing.JButton btnThucDon;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTable tblHoaDon;
        private javax.swing.JTable tblTenGia;
        private javax.swing.JLabel tienTraLai;
        private javax.swing.JLabel tongThanhToan;
        private javax.swing.JTextField txtTenNhanVien;
        private javax.swing.JTextField txtTienKhachDua;
        // End of variables declaration//GEN-END:variables
}
