/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Le Tuan Minh
 */
public class MainQuanLyFrm extends javax.swing.JFrame {

    /**
     * Creates new form MainQuanLyFrm
     */
    public MainQuanLyFrm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNhanVien = new javax.swing.JButton();
        btnThucDon = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnLenMenuDangCombo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNhanVien.setText("quản lý nhân viên");
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        btnThucDon.setText("quản lý thực đơn");
        btnThucDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThucDonActionPerformed(evt);
            }
        });

        btnHoaDon.setText("quản lý hoá đơn");
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnLenMenuDangCombo.setText("lên menu dạng combo");
        btnLenMenuDangCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLenMenuDangComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnThoat))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(60, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnLenMenuDangCombo)
                                        .addComponent(btnHoaDon)
                                        .addComponent(btnThucDon)
                                        .addComponent(btnNhanVien))
                                .addGap(54, 54, 54)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnNhanVien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnThucDon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHoaDon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLenMenuDangCombo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78,
                                        Short.MAX_VALUE)
                                .addComponent(btnThoat)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLenMenuDangComboActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLenMenuDangComboActionPerformed
        this.dispose();// GEN-FIRST:event_btnNhanVienActionPerformed
        new QuanLyComboFrm().setVisible(true);// TODO add your handling code here:
    }// GEN-LAST:event_btnLenMenuDangComboActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();// GEN-FIRST:event_btnNhanVienActionPerformed
        new QuanLyNhanVienFrm().setVisible(true);// TODO add your handling code here:
    }// GEN-LAST:event_btnNhanVienActionPerformed

    private void btnThucDonActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();// GEN-FIRST:event_btnNhanVienActionPerformed
        // GEN-FIRST:event_btnThucDonActionPerformed
        new QuanLyThucDonFrm().setVisible(true);// TODO add your handling code here:
    }// GEN-LAST:event_btnThucDonActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();// GEN-FIRST:event_btnNhanVienActionPerformed
        // GEN-FIRST:event_btnHoaDonActionPerformed
        new QuanLyHoaDonFrm().setVisible(true);// TODO add your handling code here:
    }// GEN-LAST:event_btnHoaDonActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();// TODO add your handling code here:
    }// GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainQuanLyFrm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainQuanLyFrm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainQuanLyFrm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainQuanLyFrm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainQuanLyFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnLenMenuDangCombo;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThucDon;
    // End of variables declaration//GEN-END:variables
}
